services:
  - type: web
    name: stripe-bypass-api
    runtime: node
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BEARER_TOKEN
        generateValue: true
        sync: false
      - key: LOG_SECRET
        generateValue: true
        sync: false
      - key: STRIPE_API
        value: https://api.stripe.com
    healthCheckPath: /health
    autoDeploy: true
